USE URLShortener
GO

CREATE TABLE URLS
(
	ID int	IDENTITY(1,1) PRIMARY KEY,
	URL varchar(128) NOT NULL,
	Created_DT DateTime,
	LastUsed_DT DateTime
)
GO

CREATE OR ALTER PROCEDURE SetUrl
	@URL VARCHAR(128)
AS
BEGIN TRANSACTION
	IF EXISTS (SELECT 1 FROM URLS WHERE URL = @URL )
		BEGIN
			UPDATE URLS
			SET LASTUSED_DT = SYSDATETIME()
			WHERE URL = @URL
			SELECT ID 
			FROM URLS 
			WHERE URL = @URL
		END
	ELSE
		BEGIN
			INSERT INTO URLS(URL,CREATED_DT,LASTUSED_DT)
			VALUES(@URL,SYSDATETIME(),SYSDATETIME())
		
			SELECT ID
			FROM URLS
			WHERE URL = @URL
			COMMIT
		END
GO

CREATE OR ALTER PROCEDURE GetURL
	@ID int
AS
BEGIN TRANSACTION
	SELECT URL 
	FROM URLS
	WHERE ID = @ID

GO
